version: "3.4"

services:
  ms-template-microservice:
    container_name: ms-template-microservice
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - 7701:8000
    environment:
      FLASK_ENV: development
